# Site settings
title: JennyHoney Blog
email: support@78lab.com
description: > # Memo emotion, See emotion.
baseurl: "" # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown #redcarpet

permalink: /blog/:title